Input_List = list()
for i in range(1):
	Input_List.append(input("Enter your first name: "))
	Input_List.append(input("Enter your last name: "))
	Input_List.append(int(input("Enter your age: ")))
	Input_List.append(input("Enter your email: "))
	Input_List.append(input("Enter your address: "))
	Input_List.append(input("Enter your qualification: "))
	Input_List.append(float(input("Enter your salary: ")))

print()
print(Input_List)
print()
print (f"Your First name is: {Input_List[0]}")
print (f"Your Last name is: {Input_List[1]}")
print (f"Your Age is: {Input_List[2]}")
print (f"Your Email is: {Input_List[3]}")
print (f"Your Address is: {Input_List[4]}")
print (f"Your Qualification is: {Input_List[5]}")
print (f"Your Salary is: {Input_List[6]}")
